기능: 외부 채널에서 주문 및 상품 정보 데이터 받아오기
gomicorp/EcommerceAPI pull request #118
Opened 2020-11-18 14:30 UTC by heozeop

# ExternalChannel->Adapter
> app/adapter/*
외부 채널의 데이터를 불러 와서 사전에 정의한 데이터 대로 정리합니다.

# ExternalChannel->Service
> app/service/external_channel/*
사전에 정의한 대로 정리된 데이터를 db에 저장합니다.

2020-11-22 10:29 UTC, yhk1038 requested changes
따로 디엠으로 총평 드린 부분 챙겨주시고, 남겨드린 리뷰 코멘트 확인하셔서 챙겨주세요!

2020-11-24 07:57 UTC, heozeop commented on app/adapters/external_channel/base_adapter.rb
> +      Errno::ETIMEDOUT, 'Timeout::Error',
이 부분은 Faraday gem의 default exception을 따라 사용하였습니다. 내부 구현을 보니 결국 class name을 가지고 비교하는 경우가 있어서 해당 부분을 별도 표기 없이 사용하였습니다. 하나로 맞추는것이 좋을까요?

2020-11-24 07:58 UTC, PLUX-KR commented on app/models/external_channel_cart_item.rb
> +  has_one :product_option, class_name: 'ProductOption'
has_one :product_option을 belongs_to :product_option으로 변경했습니다
관계 설정을 잘못했었네요

2020-11-24 07:58 UTC, heozeop commented on app/adapters/external_channel/base_adapter.rb
> +      Faraday::TimeoutError, Faraday::RetriableResponse, 'Net::OpenTimeout',
중복되는데 계속 안잡혀서 따로 처리 했었습니다. 이부분 짚어주셔서 감사합니다.
계속 안잡혔던 이유는 paraday에서 post메소드에 대해 기본 exception handling을 해주지 않는데 시도를 하다보니 발생한 것이었습니다. 수정하겠습니다.

2020-11-24 07:58 UTC, heozeop commented on app/adapters/external_channel/adapter_factory.rb
> +        ExternalChannel::HaravanAdapter.new
감사합니다. 수정하겠습니다.

2020-11-24 08:01 UTC, heozeop commented on config/routes.rb
> +  namespace :external_channels do
넵!

2020-11-24 08:07 UTC, heozeop commented on app/adapters/external_channel/base_adapter.rb
> +
응답 객체를 그대로 리턴하는 방식으로 수정하겠습니다.

2020-11-24 08:11 UTC, PLUX-KR commented on Gemfile
> +gem 'lazop_api_client', git: 'https://github.com/kfit-dev/lazop-api-client'
라자다가 공식 API 문서를 통해서 사용하라고 말하는 젬인데 그냥 Faraday로 시도해볼까요?

2020-11-24 08:15 UTC, PLUX-KR commented on app/models/external_channel_product_id.rb
> +# == Schema Information
어떤 의도로 말씀하신건지 알려주시면 명확한 답변을 드릴 수 있을 것 같습니다

2020-11-24 08:15 UTC, PLUX-KR commented on app/mailers/partner/membership_mailer.rb
> +    HOST = %w[production staging partner].include?(Rails.env) ? 'https://partner.gomicorp.com' : 'http://localhost:3000'
1. 파트너 환경은 현재 디딤돌 ec2에서 사용하고 있습니다 배포 후에 이슈 트래킹하다 어느 정도 안정되면 정리하겠습니다
2. 작업 이전에 production과 staging이 설정되어 있는 상태였는데 따로 수정하진 않았습니다.

2020-11-24 08:18 UTC, heozeop commented on app/adapters/external_channel/sendo_adapter.rb
> +        'PayLater'
배열-인덱스 방식으로 처리하겠습니다.

2020-11-24 08:19 UTC, PLUX-KR commented on config/webpack/partner.js
> +module.exports = environment.toWebpackConfig()
수정했습니다.

2020-11-24 08:20 UTC, PLUX-KR commented on config/routes.rb
> +  namespace :external_channels do
라우트 파일 분리했습니다.

2020-11-24 08:20 UTC, PLUX-KR commented on app/adapters/external_channel/haravan_adapter.rb
> +        ap query_hash
삭제했습니다.

2020-11-24 08:23 UTC, PLUX-KR commented on app/controllers/haravan/webhook_controller.rb
> +  class WebhookController < ApplicationController
삭제했습니다.

2020-11-24 08:30 UTC, heozeop commented on app/adapters/external_channel/lazada_adapter.rb
> +end
이 부분은 해결되었습니다.

2020-11-24 08:45 UTC, heozeop commented on app/adapters/external_channel/sendo_adapter.rb
> +        'PayLater'
아래 커밋에서 수정했습니다.
3ad5aad

2020-11-24 08:46 UTC, heozeop commented on app/adapters/external_channel/adapter_factory.rb
> +        ExternalChannel::HaravanAdapter.new
아래 커밋에서 수정했습니다.
647e656

2020-11-24 08:46 UTC, heozeop commented on app/adapters/external_channel/base_adapter.rb
> +      Errno::ETIMEDOUT, 'Timeout::Error',
아래 커밋에서 수정했습니다.

5ec922a

2020-11-24 08:46 UTC, heozeop commented on app/adapters/external_channel/base_adapter.rb
> +      Faraday::TimeoutError, Faraday::RetriableResponse, 'Net::OpenTimeout',
아래 커밋에서 수정했습니다.

5ec922a

2020-11-24 08:47 UTC, heozeop commented on app/adapters/external_channel/base_adapter.rb
> +
아래 커밋에서 수정했습니다.

5ec922a

2020-11-24 09:02 UTC, heozeop commented on app/adapters/external_channel/haravan_adapter.rb
> +
킹정우님이 하셨습니다 짝짝

2020-11-24 09:14 UTC, PLUX-KR commented on app/models/external_channel_product_id.rb
> +# == Schema Information
먼저 모델 생성 목적을 말씀드리자면, 
현 상태로는 외부채널 데이터를 가져오는 과정에서 외부채널의 상품 정보와 고미스토어의 상품 정보를 서로 매칭시킬 정보가 없습니다.
(매칭이란 외부채널의 정보를 이용해 고미스토어의 상품을 검색하는 것을 의미합니다.)
만약 외부채널의 상품 정보가 고미스토어의 상품 정보와 매칭 가능하게 하려면 고미의 상품 정보가 외부채널의 상품 유니크 키를 갖는게 이상적인데, 이 과정을 자동화하기에는 리스크가 크다고 판단했습니다.
(모든 판매채널이 동일 상품에 대해서 동일한 값을 같는 필드가 있어야 하므로 ex- 페이지 title 등) 
따라서 인터페이스와 사람의 힘을 이용해서 작업이 진행되어야 하지만, 지금 진행하기에는 공수가 너무 크기 때문에 일단 각 판매채널의 모든 상품 정보를 가져오기로 결정했습니다.
다만 후에 판매 채널간 상품 정보가 통합되는 것이 바람직한 모습으로 보여지므로, 이에 미리 대처할 수 있도록 위 모델을 만들고, 
Product 모델이 has_many로 위 모델을 여러 개를 가질 수 있도록 구현하여 확장성을 확보했습니다

2020-11-24 14:17 UTC, merged